--- 
jobs: 
  build: 
    dependencies: 
      - "docker build -t eu.gcr.io/${PROJECT_ID}/node-app:$CIRCLE_SHA1 ."
      - "sudo /opt/google-cloud-sdk/bin/gcloud docker -- push eu.gcr.io/${PROJECT_ID}/node-app:$CIRCLE_SHA1"
      - "sudo /opt/google-cloud-sdk/bin/kubectl set image deployment/${DEPLOYMENT_NAME} ${CONTAINER_NAME}=eu.gcr.io/${PROJECT_ID}/node-app:$CIRCLE_SHA1"
    deployment: 
      production: 
        branch: master
        commands: 
          - "echo $SERVICE_KEY > key.txt"
          - "base64 -i key.txt -d > ${HOME}/gcloud-service-key.json"
          - "sudo /opt/google-cloud-sdk/bin/gcloud auth activate-service-account ${ACCOUNT_ID} --key-file ${HOME}/gcloud-service-key.json"
          - "sudo /opt/google-cloud-sdk/bin/gcloud config set project $PROJECT_ID"
          - "sudo /opt/google-cloud-sdk/bin/gcloud --quiet config set container/cluster $CLUSTER_NAME"
          - "sudo /opt/google-cloud-sdk/bin/gcloud config set compute/zone $COMPUTE_ZONE"
          - "sudo /opt/google-cloud-sdk/bin/gcloud --quiet container clusters get-credentials $CLUSTER_NAME"
          - "sudo service docker start"
    environment: 
      CLUSTER_NAME: webapp207620-cluster
      COMPUTE_ZONE: europe-west1-b
      CONTAINER_NAME: webappp
      DEPLOYMENT_NAME: webapp-dep
      PROJECT_ID: webapp-207620
version: 2

